### ISSUE TITLE
How to add gene names on the SE plot from ROSE?

### ISSUE THREAD

**Issue by bharati-mehani** [crazyhottommy/ChIP-seq-analysis#10]
Hi @crazyhottommy,
Can you please guide, how can I add gene names to the Inflection plot from ROSE for super enhancers?
I'll appreciate your help.
Thanks

**Comment by crazyhottommy** [comment]
you will need to first assign a SuperEnhancer to its putative target gene either by nearest TSS or some other more complicated method (using chromatin looping information) and you then plot the inflection plot yourself using R.
