### ISSUE TITLE
Can ROSE handle multiple samples together?

### ISSUE THREAD

**Issue by bharati-mehani** [crazyhottommy/ChIP-seq-analysis#11]
Hi @crazyhottommy 
I am trying to use ROSE to call Super Enhancer between the two subtypes of a cancer, where each group has 5 samples. But I am not sure how to identify potential SE by handling multiple samples (together with ROSE) from each subtype and to compare these with the other subtype.
Do you have any suggestions, I'll really appreciate your help.
Thanks

**Comment by crazyhottommy** [comment]
you may want to merge 5 samples' bam files to a single one then call superEnhancer using ROSE or you call each individual bam SuperEnhancers  and then use bedtools to find the common ones in each subtype and then compare across subtypes.
