### ISSUE TITLE
Gene set enrichment on IDR peaks

### ISSUE THREAD

**Issue by asmariyaz23** [crazyhottommy/ChIP-seq-analysis#13]
Hello,

I ran ENCODE's ChIPSeq pipeline in "tf" mode. I want to do some gene set enrichment analysis on the IDR reproducible peaks. I have tried to work with the tools you mentioned such as chipenrich, however I do not get any terms that are enriched. Do you know of any tool that could help me?

Thank you,
Asma

**Comment by crazyhottommy** [comment]
you can try http://great.stanford.edu/public/html/
