### ISSUE TITLE
SICER-rewrite

### ISSUE THREAD

**Issue by endrebak** [crazyhottommy/ChIP-seq-analysis#2]
Dunno if you are interested, but if yes, you can find it at https://github.com/endrebak/epic

**Comment by crazyhottommy** [comment]
Hi,

Thanks for sharing. It looks very useful. I have tried SICER once for diffused peaks. It works well.
If you can add some usage examples and share your experience choosing parameters (window size, gap size etc), it would be very appreciated!

Thanks,
Ming

**Comment by endrebak** [comment]
Will add a user guide. Will also try to write more about how other tools differ and are better/worse in different cases. There is almost always a different best ChIP-Seq caller for each dataset (at least if you judge by the look of the peaks/regions you get).

Ps. my script also includes a way to compute the effective genome size (epic-effective) which is something many people wonder how to do. Thanks for the link.
