### ISSUE TITLE
the blog link not working

### ISSUE THREAD

**Issue by februaryfang** [crazyhottommy/ChIP-seq-analysis#4]
hello , crazyhottommy
I want to visit your blog, but the links are not working now. Do you change it ?
Links : http://crazyhottommy.blogspot.jp/search/label/CpG 
http://crazyhottommy.blogspot.jp/search/label/MeDIP-seq

FF

**Comment by crazyhottommy** [comment]
Hi,
it is working for me. 
try these http://crazyhottommy.blogspot.com/2013/12/tet1-enrichment-at-cpg-rich-promoters.html
http://crazyhottommy.blogspot.com/2014/01/medip-seq-and-histone-modification-chip.html

Tommy
