### ISSUE TITLE
NCIS scaling script

### ISSUE THREAD

**Issue by gyanmishra** [crazyhottommy/ChIP-seq-analysis#5]
I was trying to use NCIS_scaling .R script
It doesn’t happen to work on my bam files.
problem is happening  in this line

ga_ChIP<- readAligned(bamFile, type="BAM")
arugment 'type' had value 'BAM' allowable values: 'SolexaExport'
    'SolexaAlign' 'SolexaPrealign' 'SolexaRealign' 'SolexaResult'
    'MAQMap' 'MAQMapShort' 'MAQMapview' 'Bowtie' 'SOAP'

And still when i give Bowtie argument in type. Its not working

**Comment by crazyhottommy** [comment]
This script is pretty old and I do not think it is updated. The  `readGAlignments` function in GenomicRanges is preferred. `readAligned` function is just outdated and maybe not compatible with your bams.
