### ISSUE TITLE
Missing summit location when run macs2 with --broad option

### ISSUE THREAD

**Issue by AlicePsyche** [crazyhottommy/ChIP-seq-analysis#6]
Hi, tommy

Thanks for your post about MACS, it helps me a lot!

Actually I usually use Homer to call histone modification peaks. Recently, I need to use macs to "validate" my previous results. When I run 

```
macs2 callpeak -t test_rep1.bam -n test --broad -p 0.01 --nomodel --extsize 147 -g 1.4e9
```

The output files don't have NAME_summits.bed and there is no column of "absolute peak summit position" in NAME_peaks.xls. Did I miss some specific options? 

Or do you happen to know how can I quickly identify the summit location in a bed file(The most enriched signal location in a region)? I am new to bioinformatics, I write a small script to calculate the 100bp bin region FPKM then screen the max value...but it is very slow(of course).. 

Thanks for your help in advance!

**Comment by crazyhottommy** [comment]
it seems if you specify --broad, no summit will be reported by macs2. The only way to do is get a single base pair pipleup say by bedtools genomcov and then for each broad peak identified by macs2 check with base has the highest value.

I also see you asked the question on the pybigwig page. as you see, there is no direct way you can get it easily...

**Comment by AlicePsyche** [comment]
Thanks for your reply! Kind of desperate...I also asked the questions on biostar, macs, Homer 😅 New to bioinformatics, just intuitively thought it was a simple question but I could not find more elegant solution. (￣o￣) 

Thanks again, your series of ChIP-seq blog really help me a lot.

**Comment by crazyhottommy** [comment]
glad it helps! I was new too, that's why I wrote down the notes.
