### ISSUE TITLE
epic2 out in bioinformatics

### ISSUE THREAD

**Issue by endrebak** [crazyhottommy/ChIP-seq-analysis#9]
https://github.com/biocore-ntnu/epic2

https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz232/5421513

AFAIK it is by far the fastest ChIP-Seq caller :) It also fixes a bug in SICER.

Btw, you might be interested in this: https://github.com/biocore-ntnu/pyranges

Since you are using Python sometimes with Snakemake it might be more convenient than R GenomicRanges (which also is very nice :) )

**Comment by crazyhottommy** [comment]
congrats for the paper and thank you for sharing! I will try epic2 for some of my broad histone data.
added to the list. I will take a look at pyranges as well.

**Comment by endrebak** [comment]
Thanks. Love this resource :)
